# Generated by Django 3.1.7 on 2021-12-23 07:07

from django.db import migrations, models
import login_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='confirm code')),
                ('usr_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='用户邮箱')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Confirm Code',
                'verbose_name_plural': 'Confirm Codes',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='usr_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.CharField(max_length=20, unique=True, verbose_name='用户id')),
                ('usr_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='用户邮箱')),
                ('usr_pwd', models.CharField(max_length=256, verbose_name='用户密码')),
                ('usr_nkname', models.CharField(max_length=40, null=True, verbose_name='用户昵称')),
                ('usr_pic', models.ImageField(blank=True, null=True, upload_to=login_module.models.user_directory_path, verbose_name='照片')),
            ],
        ),
    ]
