# Generated by Django 3.1.7 on 2021-12-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usr_info',
            old_name='usr_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usr_info',
            old_name='usr_nkname',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='usr_info',
            old_name='usr_pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usr_info',
            old_name='usr_pic',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='usr_info',
            old_name='usr_id',
            new_name='username',
        ),
    ]
