# Generated by Django 3.1.7 on 2022-01-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0002_auto_20211223_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr_info',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='usr_info',
            name='picture',
        ),
        migrations.AddField(
            model_name='usr_info',
            name='last_path',
            field=models.CharField(default='', max_length=1024, verbose_name='上一次打开文件'),
        ),
    ]
